language: python
python:
  - "2.7"
  - "2.6"
env:
  global:
    - secure: "zyKoM1y1rTq4BIuS7LqVd0WydQwQJlF7UgkCigoIn8VEvhLXoLzVHpILRNZv\nYqk1lZwoX9th0ktvrEUFHlGqQB4VWGhMUq94MgDuNQg9cmdJdmdo9OOoheJX\nKE+HCqJOhfaPrwskS2V6IFnQUqhgylvTcK2f0UEyz0SpIXd8vI4="
    - secure: "JBBgbEFEDGlX2Ep7cbzsv9JAIWa4nTWnMFtI0DBvikkEM/W5JoM1PnZnP/Wj\nwaKWbytzc/xShM1nerh4re+1G5UZqKdvvPw/f+Ge2NJ72bkKEXxKBzGpkEAx\nMgXCwTdj8B7yRNfl3tbMQaEthlIAHeLo+ix96s8w4Max98Q1ZAo="
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install requests
# command to run tests, e.g. python setup.py test
script:  python test.py