language: python
python:
  - "2.7"
  - "2.6"
env:
  global:
    - secure: "DOCQlFRUEiVQ/Z4r9dRvkI7tStyJVlTJkFp6yOnbH/YK3WveCjIKUv2B79Up\na5TcVi7lvmEFYs8L9Rm+Ms3Z77u36QzhCIY3QwvE7jLf746jWAKZIPwo8xLD\nqia8N6gfjOMElxdbFx0HQSqhCkrWze62+C1g31Nr1NymfGbKhFU="
    - secure: "WZYImZRlT2EvtZOAasxt+zbKeJXp651ncLI8djgE1X/Hy9P2nmDb7yikKhGw\nQE6P/VSPaISVIJ39LZ1dwTmAGV2txmNiSfZ/YPw4CH784O7Y4U9wNsEhcxtd\nyhuRKjJwAZ7ZlVA87ePv38xgdbG/9DjvX4Bsz9yXobJn7SuEJ6U="    
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install requests
# command to run tests, e.g. python setup.py test
script:  python test.py